# Generated by Django 3.0.7 on 2021-12-30 08:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20211230_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Bodydata',
        ),
    ]
